name: SimpleHomes
version: '1.0.0'
main: net.milanchik.simpleHomes.SimpleHomes
api-version: '1.21'
authors: [ Milanchik ]
description: A plugin that adds homes by beds
website: https://github.com/Milanch1k
commands:
  homes:
    aliases:
      - рщьуы
      - homegui
      - home
    permission: simplehomes.homes
  simplehomes:
    permission: simplehomes.simplehomes

permissions:
  simplehomes.homes:
    default: true
  simplehomes.simplehomes:
    default: op